CREATE TABLE CGV(
	CID INT PRIMARY KEY, -- 기본키
	TITLE VARCHAR(100) NOT NULL, --영화제목
	IMAGE VARCHAR(1000) NOT NULL, --
	GENRE VARCHAR(100),
	BOOKCNT INT DEFAULT 0
);
SELECT * FROM CGV;
DROP TABLE CGV;